# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSApp-Objective-C' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSApp-Objective-C
  
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'YYKit'
  #  pod 'NXKit'

end
